/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OptionalHolidaysRouteImport } from './routes/optional-holidays'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FederalAndProvincialHolidaysRouteImport } from './routes/federal-and-provincial-holidays'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthCompleteRouteImport } from './routes/auth-complete'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionalHolidaysRoute = OptionalHolidaysRouteImport.update({
  id: '/optional-holidays',
  path: '/optional-holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FederalAndProvincialHolidaysRoute =
  FederalAndProvincialHolidaysRouteImport.update({
    id: '/federal-and-provincial-holidays',
    path: '/federal-and-provincial-holidays',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth-complete',
  path: '/auth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/auth-complete': typeof AuthCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/federal-and-provincial-holidays': typeof FederalAndProvincialHolidaysRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/optional-holidays': typeof OptionalHolidaysRoute
  '/policies': typeof PoliciesRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/tiers': typeof TiersRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/federal-and-provincial-holidays'
    | '/health'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/tiers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/federal-and-provincial-holidays'
    | '/health'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/tiers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access'
    | '/auth-complete'
    | '/dashboard'
    | '/departments'
    | '/federal-and-provincial-holidays'
    | '/health'
    | '/login'
    | '/logout'
    | '/optional-holidays'
    | '/policies'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/tiers'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessRoute: typeof AccessRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FederalAndProvincialHolidaysRoute: typeof FederalAndProvincialHolidaysRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OptionalHolidaysRoute: typeof OptionalHolidaysRoute
  PoliciesRoute: typeof PoliciesRoute
  PostsRoute: typeof PostsRoute
  ProfileRoute: typeof ProfileRoute
  RolesRoute: typeof RolesRoute
  TiersRoute: typeof TiersRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optional-holidays': {
      id: '/optional-holidays'
      path: '/optional-holidays'
      fullPath: '/optional-holidays'
      preLoaderRoute: typeof OptionalHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federal-and-provincial-holidays': {
      id: '/federal-and-provincial-holidays'
      path: '/federal-and-provincial-holidays'
      fullPath: '/federal-and-provincial-holidays'
      preLoaderRoute: typeof FederalAndProvincialHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete': {
      id: '/auth-complete'
      path: '/auth-complete'
      fullPath: '/auth-complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessRoute: AccessRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  FederalAndProvincialHolidaysRoute: FederalAndProvincialHolidaysRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OptionalHolidaysRoute: OptionalHolidaysRoute,
  PoliciesRoute: PoliciesRoute,
  PostsRoute: PostsRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  TiersRoute: TiersRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
